// Generated by CoffeeScript 1.3.3
(function() {
  var Axle, http, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  http = require("http");

  _ = require("underscore");

  Axle = (function() {

    function Axle() {}

    Axle.prototype.getOptions = function(path) {
      var headers, options;
      if (this.domain == null) {
        throw new Error("No domain set.");
      }
      headers = {
        "Host": this.domain,
        "User-Agent": "axle-node HTTP client",
        "Content-type": "application/json"
      };
      return options = {
        hostname: this.domain,
        port: this.port,
        path: this.path(path),
        headers: headers
      };
    };

    Axle.prototype.parseResponse = function(res, cb) {
      var body;
      res.setEncoding("utf8");
      body = [];
      res.on("data", function(chunk) {
        return body.push(chunk);
      });
      return res.on("end", function() {
        var body_str, error_details;
        body_str = body.join("");
        if (res.statusCode === !200) {
          error_details = {
            status: res.statusCode,
            body: body_str
          };
          cb(error_details, null);
        }
        return cb(null, JSON.parse(body_str));
      });
    };

    Axle.prototype.poster = function(path, params, cb) {
      var options, req,
        _this = this;
      options = this.getOptions(path);
      options.method = "POST";
      req = http.request(options, function(res) {
        return _this.parseResponse(res, cb);
      });
      req.write(JSON.stringify(params));
      return req.end();
    };

    Axle.prototype.getter = function(path, cb) {
      var options, req,
        _this = this;
      options = this.getOptions(path);
      req = http.request(options, function(res) {
        return _this.parseResponse(res, cb);
      });
      return req.end();
    };

    return Axle;

  })();

  exports.V1 = (function(_super) {

    __extends(V1, _super);

    function V1(domain, port) {
      this.domain = domain;
      this.port = port != null ? port : 3000;
      this.path_prefix = "/v1";
    }

    V1.prototype.path = function(extra) {
      return this.path_prefix + extra;
    };

    V1.prototype.getKeysByApi = function(api, options, cb) {
      var defaults, endpoint, params;
      defaults = {
        from: 0,
        to: 10
      };
      params = _.extend(defaults, options);
      endpoint = "/api/" + api + "/keys/" + params.from + "/" + params.to;
      return this.getter(endpoint, cb);
    };

    V1.prototype.getApis = function(options, cb) {
      var defaults, endpoint, params;
      defaults = {
        from: 0,
        to: 10,
        resolve: false
      };
      params = _.extend(defaults, options);
      endpoint = "/apis?from=" + params.from + "&to=" + params.to + "&resolve=" + params.resolve;
      return this.getter(endpoint, cb);
    };

    V1.prototype.createApi = function(api, endpoint, options, cb) {
      var api_endpoint, defaults, params;
      defaults = {
        endPoint: endpoint
      };
      params = _.extend(defaults, options);
      api_endpoint = "/api/" + api;
      return this.poster(api_endpoint, params, cb);
    };

    V1.prototype.createKey = function(key, api, options, cb) {
      var api_endpoint, defaults, params;
      defaults = {
        forApi: api
      };
      params = _.extend(defaults, options);
      api_endpoint = "/key/" + key;
      return this.poster(api_endpoint, params, cb);
    };

    return V1;

  })(Axle);

}).call(this);
